on:
  pull_request: {}
  push: {}

jobs:
  formatting:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run formatting

  spelling:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run spelling

  audit:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm audit --audit-level high

  test:
    runs-on: ubuntu-latest
    container: node:22.5.1-alpine3.19
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm test
